[project]
dependencies = [
  "yt-dlp>=2025.9.5",
]
description = "fe-250228"
name = "fe-250228"
readme = "README.md"
requires-python = ">=3.13"
version = "0.1.0"

[dependency-groups]
dev = [
  "ruff>=0.12.12",
]
